### ISSUE TITLE
error when pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by iipeace** [guiderOrg/visualizer#12]
```
ERROR: Cannot install -r requirements.txt (line 5) and urllib3==1.26.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.5
    botocore 1.17.6 depends on urllib3<1.26 and >=1.20; python_version != "3.4"
```

please refer to [this](https://github.com/duo-labs/cloudmapper/issues/875)

**Comment by yoonje** [comment]
This is fixed by https://github.com/guiderOrg/visualizer/pull/13

**Comment by yoonje** [comment]
The library version was the problem. I solved it by doing a rollback.

**Comment by yoonje** [comment]
SyntaxWarning fixed https://github.com/guiderOrg/visualizer/pull/13

**Comment by iipeace** [comment]
thanks!

**Comment by GohEeEn** [comment]
Hi I am still getting this exact error from the latest `main` repository when building on MacOS. May I know did I miss something ?
<img width="1069" alt="Screenshot 2021-10-20 at 15 38 23" src="https://user-images.githubusercontent.com/34720382/138114745-9804be96-9b23-4657-b548-23b1723c1529.png">

Thanks in advances !
